project:
  type: website

website:
  title: "Katlyn Bagley-Sepsey"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: resources.qmd
        text: Resources
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

